PRODUCT_TYPE_STOCK = "STOCK"
PRODUCT_TYPE_SERVICE = "SERVICE"
PRODUCT_TYPE_NON_STOCK = "NON_STOCK"
PRODUCT_TYPE_BUNDLE = "BUNDLE"

PRODUCT_CLASS_GOODS = "GOODS"
PRODUCT_CLASS_SERVICE = "SERVICE"
PRODUCT_CLASS_INS = "INS"

ASSET_TYPE_NORMAL = "NORMAL"
ASSET_TYPE_FIXED_ASSET = "FIXED_ASSET"

VALUATION_FIFO = "FIFO"
VALUATION_AVG = "WEIGHTED_AVERAGE"
VALUATION_LPC = "LAST_PURCHASE_COST"